export const ECOSYSTEM_NODES = [
  {
    id: 'ideas',
    name: 'IDEAS',
    icon: 'Lightbulb',
    title: 'IDEAS',
    description:
      'A space for curious minds to explore real problems, brainstorm freely, and shape ideas into meaningful solutions.',
    targetId: 'initiatives',
    basePos: [-2.55, 1.45, 0.35],
    ringIndex: 1,
    ringAngle: 2.38,
    labelAlign: 'left-top',
  },
  {
    id: 'students',
    name: 'STUDENTS',
    icon: 'Users',
    title: 'STUDENTS',
    description:
      'A growing community of builders, thinkers, and doers at RCPIT learning entrepreneurship by practice.',
    targetId: 'members',
    basePos: [-2.95, 0.05, 0.1],
    ringIndex: 0,
    ringAngle: Math.PI,
    labelAlign: 'left-mid',
  },
  {
    id: 'events',
    name: 'EVENTS',
    icon: 'Calendar',
    title: 'EVENTS',
    description:
      'Hackathons, pitch nights, workshops, and summits that put ideas in front of the people who matter.',
    targetId: 'events',
    basePos: [-2.55, -1.45, -0.25],
    ringIndex: 2,
    ringAngle: 3.92,
    labelAlign: 'left-bot',
  },
  {
    id: 'startups',
    name: 'STARTUPS',
    icon: 'Rocket',
    title: 'STARTUPS',
    description:
      'Support for early ventures with validation, resources, and a path from prototype to launch.',
    targetId: 'initiatives',
    basePos: [2.55, 1.45, -0.35],
    ringIndex: 2,
    ringAngle: 0.78,
    labelAlign: 'right-top',
  },
  {
    id: 'mentors',
    name: 'MENTORS',
    icon: 'GraduationCap',
    title: 'MENTORS',
    description:
      'Founders, alumni, and industry experts who guide teams from first draft to first customer.',
    targetId: 'team',
    basePos: [2.95, 0.05, 0.2],
    ringIndex: 0,
    ringAngle: 0,
    labelAlign: 'right-mid',
  },
  {
    id: 'partners',
    name: 'PARTNERS',
    icon: 'Handshake',
    title: 'PARTNERS',
    description:
      'Industry, incubators, and institutions that open doors to funding, tools, and real opportunities.',
    targetId: 'partners',
    basePos: [2.55, -1.45, 0.25],
    ringIndex: 1,
    ringAngle: 5.52,
    labelAlign: 'right-bot',
  },
];
